PROTOALPHA-2295: adding links to classic and some rewording
BBCConnectedStudio/documentation pull request #14
Opened 2017-05-08 15:36 UTC by Lathrisk

@ospall @jackallnutt @dwalees @yakca Ready for Review

2017-05-09 10:40 UTC, jackallnutt requested changes

2017-05-09 10:40 UTC, jackallnutt commented on technical/standalone-pilot-integration-steps.md
> +We have developed two badges. One of these will sit within your pilot; enabling rating, sharing, and survey feedback, as well as basic analytics. The two versions which are currently available are th
I don't think a semicolon should be used that. Perhaps the following would work better:

> We have developed two badges, one of which will sit within your pilot. These badges enable rating, sharing, and survey feedback, as well as basic analytics.

2017-05-09 10:47 UTC, jackallnutt approved these changes

2020-01-20 18:19 UTC, yakca commented
Out of date with merge conflict; closing this.

2020-01-20 18:19 UTC, closed without merging